### ISSUE TITLE
0.7.4 super slow at "Downloading State" -- still an issue in 0.7.6

### ISSUE THREAD

**Issue by aleqx** [GrinPlusPlus/GrinPlusPlus#109] opened 2020-01-26 15:00 UTC
I just upgraded to 0.7.4 on Windows 8.1. 

`2/4 Downloading State (13%)` but `2/4 Downloading State (8%)` was about 1h ago ... it 5% in 1h.

0.7.3 did all of it in a snap (minutes, possible less than 1 minute). Didn't look at the code to see what changed but something seems fishy ... unless you intended for 0.7.4 to do some in depth parsing the first time it runs after upgrading?

**Comment by DavidBurkett** [comment] 2020-01-26 15:15
It depends on the peer you get, but it should've timed out by then. Try closing Grin++, deleting `%userprofile%/.GrinPP/MAINNET/NODE/TXHASHSET` and `%userprofile%/.GrinPP/MAINNET/NODE/DB/PEERS` and reopening it.

**Comment by aleqx** [comment] 2020-01-26 15:16
It shows: https://i.gyazo.com/eea510aa031ed43cf53b60c4c48c334b.png ... but isn't it supposed to connect to multiple peers anyway, like the official wallet does?

**Comment by DavidBurkett** [comment] 2020-01-26 15:18
For the txhashset (downloading state), the official wallet also only uses a single peer. Of course you're connected to more, but for that step, it's just downloading a big zip file, and can't do it in parallel. So it just chooses a peer.

I'm designing a sync process that gets rid of the zip and downloads pieces in parallel, but it will be a while, since it has to go through the RFC review process.

**Comment by aleqx** [comment] 2020-01-26 15:23
Never looked at that side of the code so I didn't know ... maybe we should ban slow nodes at the protocol level as they can do more harm than good by delaying everything (think block propagation too)

**Comment by aleqx** [comment] 2020-01-26 15:27
Hmm, so I stopped, deleted the folders you suggested, restarted, then it said 2/4 Downloading State *twice* (as in, it went from 0% to 100% twice at step 2/4) then it said "Not connected" and it just sits there.

**Comment by DavidBurkett** [comment] 2020-01-26 17:13
> Never looked at that side of the code so I didn't know, and it seems I have been lucky until now ... maybe we should ban slow nodes at the protocol level as they can do more harm than good by delaying everything (think block propagation too)

I discussed this with Igno in the past and he was opposed to banning slower peers. And to be fair, there are a lot of people with slow connections running Grin that would probably be kicked off the network.

**Comment by DavidBurkett** [comment] 2020-01-26 17:14
> Hmm, so I stopped, deleted the folders you suggested, restarted, then it said 2/4 Downloading State _twice_ (as in, it went from 0% to 100% twice, both "2/4" ... ?) then it said "Not connected" and it just sits there.

That's strange. Try deleting TXHASHSET again. I think some nodes are serving bad txhashset's again (was a huge problem before the fork), and I think Grin++ is failing to unlock the TXHASHSET folder when it fails, causing all future downloads to fail as well. I'm working on cleaning up that logic right now to see if I can improve the situation.

**Comment by aleqx** [comment] 2020-01-26 19:55
> there are a lot of people with slow connections running Grin that would probably be kicked off the network

Thanks not necessarily a bad thing!

>  Try deleting TXHASHSET again. 

Did so 3 times. Each time it took ages and it did the same step 2/4 multiple times in the same session (what gives?). Eventually it got there but it was a pain.

> I think Grin++ is failing to unlock the TXHASHSET folder

What do you mean by "unlock". The folder was inexistent before Grin++ started every time.

**Comment by Niels86** [comment] 2020-01-27 08:22
Same problem, here. Grin++ kept on repeating step 2 Loading State, when finished it just starts over again loading again. I tried what you suggested and it worked, the process now continued normally through step 3 and step 4.

**Comment by perre78** [comment] 2020-01-28 21:01
Just upgraded to 0.7.5 and having the same issue. I have deleted the folders above but after "2/4 Downloading State" it restarts with the same status. But after a couple of loops it continued to "3/4 Validating State" and then finished the sync process. I noticed the peer count (?) (green arrow) is lower than previous versions.

**Comment by aleqx** [comment] 2020-02-25 16:06
Problem still persists in 0.7.6 ... I just upgraded and it already did "2/4 Downloaded State" three times. Now it's doing it for the fourth time. No idea when/if it ever gets out of ...

**Comment by DavidBurkett** [comment] 2020-02-25 19:26
@aleqx Can you send me your logs? I've identified the cause and patched it on win10, so it's likely there's a difference in how win8.1 locks files.

**Comment by aleqx** [comment] 2020-02-25 19:30
I deleted TXHASHSET and DB/PEERS and then it worked.

**Comment by DavidBurkett** [comment] 2020-02-25 19:32
Logs would still be beneficial since I can't recreate this.

**Comment by aleqx** [comment] 2020-02-25 19:32
Sure, which log file in particular would you like?

**Comment by DavidBurkett** [comment] 2020-02-25 19:34
%userprofile%/.GrinPP/MAINNET/LOGS/Node.log. Preferably all of the logs that start with `Node` if you can zip them up for me.

**Comment by aleqx** [comment] 2020-02-25 19:44
Here you go [Node.zip](https://github.com/GrinPlusPlus/GrinPlusPlus/files/4251833/Node.zip)

**Comment by aleqx** [comment] 2020-02-25 19:47
I only now noticed that this log shows tx commitments which i wouldn't have wanted in the public domain ... something to keep in mind when requesting logs from people

**Comment by DavidBurkett** [comment] 2020-02-25 20:06
Sorry, I couldn't remember if your own commitments were shown in node logs, or just wallet logs. In the future, you may email logs directly. My email is on my github profile.

**Comment by DavidBurkett** [comment] 2020-02-26 12:25
@aleqx The logs indicate you're running old code. That means either something failed when building the update, or something failed when you installed the update.

**Comment by aleqx** [comment] 2020-02-26 12:34
https://i.gyazo.com/56db3ed8e2e100cbdd82cea9e27d286a.png

**Comment by DavidBurkett** [comment] 2020-02-26 12:37
Yea, I think it's the former issue, not the latter. I'm going to release 0.7.7, because I think the 0.7.6 release didn't pull the latest code for some reason.

**Comment by aleqx** [comment] 2020-02-27 13:47
Ok, will try out 0.7.7 and let you know.

**Comment by perre78** [comment] 2020-02-29 14:34
0.7.7 Works great 😊 Skickades från E-post för Windows 10 Från: aleqxSkickat: den 27 februari 2020 14:47Till: GrinPlusPlus/GrinPlusPlusKopia: perre78; ManualÄmne: Re: [GrinPlusPlus/GrinPlusPlus] 0.7.4 super slow at "Downloading State" -- still an issue in 0.7.6 (#109) Ok, will try out 0.7.7 and let you know.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aleqx** [comment] 2020-03-02 14:56
Induced a few days pause then started 0.7.7, which did stages 1,2,3/4 quickly (few seconds) and then to stage 4/4 to sync blocks. So far so good.

p.s. Block sync'ing still slower than the official wallet (it's always been like that, doesn't look like it's the peers)

**Comment by DavidBurkett** [comment] 2020-03-02 15:02
Block syncing used to be 10x faster than official wallet, but they've made a lot of improvements, so the situation could be far different now. Out of curiousity, what kind of specs are you running on?

**Comment by DavidBurkett** [comment] 2020-04-12 08:47
Block sync has been improved in 1.0.0

**Closed by DavidBurkett** 2020-04-12 08:47 UTC

**Comment by Niels86** [comment] 2020-05-13 10:40
Hi David, syncing has become a problem again for me (v 1.0.2). The Syncing blocks part was stuck, so I tried the old method of deleting %userprofile%/.GrinPP/MAINNET/NODE/TXHASHSET and %userprofile%/.GrinPP/MAINNET/NODE/DB/PEERS. When opening Grin++ it appears to load forever before login. What worse, when I restored the folders, it is still stuck in limbo. Do I need to reinstall, any advice?

**Comment by DavidBurkett** [comment] 2020-05-13 16:16
Hi @Niels86, that was a specific fix for a well known problem that's been fixed now. Since some of your node data was deleted now, you're probably best off just deleting the whole %userprofile%/.GrinPP/MAINNET/NODE folder and letting it resync

**Comment by Niels86** [comment] 2020-05-13 18:02
Thanks @DavidBurkett, that solved it.
