### ISSUE TITLE
Receiving (Unconfirmed)

### ISSUE THREAD

**Issue by artdmo** [GrinPlusPlus/GrinPlusPlus#141] opened 2020-07-30 19:13 UTC
![1](https://user-images.githubusercontent.com/60815664/88963875-6a67a880-d2a0-11ea-81cf-feb6bc75140c.jpg)

i'm receiving Grin from mining 
is that issue with wallet or pool ?

**Comment by DavidBurkett** [comment] 2020-07-30 19:19
Most likely a pool issue, but hard to say for sure. Are you running 1.1.3?

**Comment by artdmo** [comment] 2020-07-30 19:21
Yes

**Comment by artdmo** [comment] 2020-07-30 19:24
but i didn't have any problem on version 1.0.6

**Comment by DavidBurkett** [comment] 2020-07-30 20:30
The pool's support should be able to tell you why it failed. Which pool are you using?

**Comment by artdmo** [comment] 2020-07-30 20:47
2Miners

**Comment by artdmo** [comment] 2020-07-31 06:33
i have written to pool support
and got information  that my wallet should be online

i have reinstall grin wallet and i get this now 
![2](https://user-images.githubusercontent.com/60815664/89007106-007eeb80-d300-11ea-9582-20571cbd16ac.JPG)

**Comment by DavidBurkett** [comment] 2020-07-31 06:46
Your wallet was online, which is how the unconfirmed transactions showed up in the first place.

Did restarting the wallet get rid of that message?

**Comment by artdmo** [comment] 2020-07-31 07:55
maybe wallet posible losing connection
i got that message 3 time so far from update

now im awaiting peers after resync
![3](https://user-images.githubusercontent.com/60815664/89012335-f235cd00-d309-11ea-943c-16b4792d3463.JPG)

**Comment by DavidBurkett** [comment] 2020-08-01 08:41
> now im awaiting peers after resync

Did this ever resolve? If not, close Grin++ and delete `%userprofile%/.GrinPP/MAINNET/NODE` and then reopen. That's a hard resync that will hopefully resolve it

**Comment by artdmo** [comment] 2020-08-01 16:38
I believe this is related to the Grin Hard fork , can't collect any Grin from pool after that
![1](https://user-images.githubusercontent.com/60815664/89105947-7d53b780-d41d-11ea-91d8-c2e56ffd54f1.JPG)

**Comment by shrikus** [comment] 2020-08-01 19:21
we checked this problem from the pool side, and we have one error for all grinplusplus payments:
```
Fee Dispute Error: 0, 12000000
```

**Comment by DavidBurkett** [comment] 2020-08-01 20:06
> we checked this problem from the pool side, and we have one error for all grinplusplus payments:

Thanks @shrikus. Do you guys use a custom grin-wallet version? "Compact slates", which were introduced in 4.0.0, and are now the only supported slate methods, repopulate the fee during finalize, as seen here: https://github.com/mimblewimble/grin-wallet/blob/master/libwallet/src/api_impl/owner.rs#L767

For some reason, your pool doesn't appear to be repopulating the fee from the fee originally set. The "receive" step using compact slates removes fee from the slate before returning it, since the sender already knows the fee. It appears the pool (aka the sender) forgets to do that, and so is attempting to build the transaction with no fee. 

Here's what happens during finalize:
1. owner::finalize_tx calls repopulate_tx with update_fee=true https://github.com/mimblewimble/grin-wallet/blob/6c9cef137006eb6b3c63635edcf300c03700d0c0/libwallet/src/api_impl/owner.rs#L767
2. selection::repopulate_tx updates fee using original value https://github.com/mimblewimble/grin-wallet/blob/6c9cef137006eb6b3c63635edcf300c03700d0c0/libwallet/src/internal/selection.rs#L666
3. owner::finalize_tx calls complete_tx https://github.com/mimblewimble/grin-wallet/blob/6c9cef137006eb6b3c63635edcf300c03700d0c0/libwallet/src/api_impl/owner.rs#L769
4. tx::complete_tx calls Slate.finalize https://github.com/mimblewimble/grin-wallet/blob/0e817fd1c0d6b94514538c03bf1ede35a1413e4b/libwallet/src/internal/tx.rs#L285
5. Slate.finalize calls finalize_transaction https://github.com/mimblewimble/grin-wallet/blob/6c9cef137006eb6b3c63635edcf300c03700d0c0/libwallet/src/slate.rs#L432
6. finalize_transaction calls check_fees, which is where that error is thrown. But fee should've already been updated in step 2.  https://github.com/mimblewimble/grin-wallet/blob/6c9cef137006eb6b3c63635edcf300c03700d0c0/libwallet/src/slate.rs#L670

**Comment by DavidBurkett** [comment] 2020-08-01 20:10
@Yeastplume Can you verify that the claims about the compact slates flow in my previous message are all accurate? I'm happy to make a fix if I'm misunderstanding something, but I don't see how 2miners is able to pay out to any grin-wallet using compact slates if they're not repopulating fee during finalize.

**Comment by shrikus** [comment] 2020-08-01 20:13
we are use standard grin-wallet 4.0.0, and posting transactions via init_send_tx with args like this:

```
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "init_send_tx",
  "params": {
    "args": {
      "amount": "988000000",
      "estimate_only": null,
      "max_outputs": 10,
      "minimum_confirmations": 1,
      "num_change_outputs": 2,
      "payment_proof_recipient_address": null,
      "selection_strategy_is_use_all": false,
      "send_args": {
        "dest": "http://k7cahdecuvx2267txsu6vulbh7y7dhqbm277pkutiquicnqoctvuqfad.grinplusplus.com",
        "finalize": true,
        "fluff": false,
        "post_tx": true,
        "skip_tor": false
      },
      "src_acct_name": null,
      "target_slate_version": 3,
      "ttl_blocks": null
    },
    "token": "xxx"
  }
}
```

**Comment by DavidBurkett** [comment] 2020-08-01 20:23
That ends up calling owner::finalize_tx, so should go through the exact flow I described. https://github.com/mimblewimble/grin-wallet/blob/7a003374ac0d0189df0041edffaf332f4ded2d26/api/src/owner.rs#L691

Do you happen to log out what the wallet sends to the receiver's foreign receive_tx API, and what it gets in return?

**Comment by artdmo** [comment] 2020-08-01 21:26
![1](https://user-images.githubusercontent.com/60815664/89110694-34175e00-d445-11ea-8768-2da0320609ee.JPG)
![2](https://user-images.githubusercontent.com/60815664/89110696-34aff480-d445-11ea-8036-f94d6ab8dc84.JPG)
![3](https://user-images.githubusercontent.com/60815664/89110697-34aff480-d445-11ea-8a15-2b860f6b7ed4.JPG)
![4](https://user-images.githubusercontent.com/60815664/89110698-35488b00-d445-11ea-9611-da68784dedee.JPG)
![5](https://user-images.githubusercontent.com/60815664/89110699-35488b00-d445-11ea-84e2-d6f543194d29.JPG)
![6](https://user-images.githubusercontent.com/60815664/89110701-35e12180-d445-11ea-9df0-649affbd4649.JPG)
![7](https://user-images.githubusercontent.com/60815664/89110703-35e12180-d445-11ea-8709-b6adfbb8b2a0.JPG)
![8](https://user-images.githubusercontent.com/60815664/89110704-3679b800-d445-11ea-8322-d747c8dafe05.JPG)

maybe that help
i got different fee

**Comment by DavidBurkett** [comment] 2020-08-03 14:10
@shrikus, Yeastplume has confirmed that Grin++ is doing the right thing by stripping out the fee before returning back to the sender. There must be an issue with the grin-wallet used by 2miners. Do you guys build from source, or do you download the pre-built grin-wallet release?

![image](https://user-images.githubusercontent.com/24623306/89191791-71790a00-d571-11ea-9064-e7b7f74f1a9f.png)

**Comment by shrikus** [comment] 2020-08-03 14:58
we use release pre-build binary

```
20200801 20:57:31.337 INFO grin_wallet - This is Grin Wallet version 4.0.0 (git v4.0.0), built for x86_64-unknown-linux-gnu by rustc 1.44.1 (c7087fe00 2020-06-17).
```

**Comment by Niels86** [comment] 2020-08-11 07:47
Any update on this issue? I got some funds on 2miners which are received but not confirmed. Also I get frequently the warning "The node process stopped running, this is unusual but dont worry, restarting will resolve it" or something similar with Grin++ v1.1.3. 
So possibly it is an issue with my Grin++ installation.

**Comment by slavikus** [comment] 2020-08-19 16:23
@DavidBurkett is there anything we could do from our side to help diagnose the problem? We're using the pre-built binary from the github and technically are not doing anything custom to send the transaction as other customers are receiving the funds successfully.

**Comment by davidtavarez** [comment] 2020-08-20 05:08
@slavikus is this the version are you using https://github.com/mimblewimble/grin-wallet/releases/tag/v4.0.0 ?

**Comment by slavikus** [comment] 2020-08-20 12:18
@davidtavarez that is correct, we use exactly the binary associated with that release.

**Comment by davidtavarez** [comment] 2020-08-20 13:08
@slavikus I will let my wallet running with the latest binary of Grin++ would you mind to send a test?

grin1mtuttne400y2k5wf203fnd4uvlq6l582qjnq7gcfhjpglnkl4r6sn6ljs0
http://3l4lltzvppekwuojkprjtnv4m7a27uhkasta6iyjxsbi7tw7vd2w2nad.grinplusplus.com/

it will be running for at least 4 hours

**Comment by davidtavarez** [comment] 2020-08-20 13:41
let's see...

![1minuteAgo](https://user-images.githubusercontent.com/337107/90777361-97d1d000-e2fb-11ea-8b28-5a13533d2cd2.png)

**Comment by oneevil** [comment] 2020-08-20 13:41
Daemon failed to process payment: RPC Error: Fee: Fee Dispute Error: 0, 12000000

**Comment by oneevil** [comment] 2020-08-20 13:43
`{"id":1,"jsonrpc":"2.0","method":"init_send_tx","params":{"args":{"amount":"85000000","estimate_only":null,"max_outputs":10,"minimum_confirmations":1,"num_change_outputs":2,"payment_proof_recipient_address":null,"selection_strategy_is_use_all":false,"send_args":{"dest":"http://3l4lltzvppekwuojkprjtnv4m7a27uhkasta6iyjxsbi7tw7vd2w2nad.grinplusplus.com","finalize":true,"fluff":false,"post_tx":true,"skip_tor":false},"src_acct_name":null,"target_slate_version":3,"ttl_blocks":null},"token":"-delete-"}}`

**Comment by davidtavarez** [comment] 2020-08-20 13:51
```
[08/20/20 15:39:35.783+02:00] [info] [THREAD:18612] Handle(78) - REQUEST: {"id":1,"jsonrpc":"2.0","method":"receive_tx","params":[{"amt":"85000000","coms":[{"c":"08262dfa573c9670d9c2f72bc4f8f955f0a956e43b3fe17e1a37e2f086a44c63ef"},{"c":"096dccb99f949be8acd96957289f91ec44b5b6dd846499d0970aed1d13642f63cc","p":"2c9a5fdb98f60901e7d6acfd6484be2d1fbe2d6c0d8ebe4f92d7e6aadf673ce41d9e01e93eb98065df548216d14e971ff09d52051ebe0675fa3e8be2027251d30e10ae3ae6177dd44d831014dce1ed81854fbcd20b70a948bdd8a0f238003a61ac69319e9f4c1fe2e0a47632634db3e05237b377a3c640e5aacbe787b9da5b4efafe91943db48c85eb16df0ded9951dc8b8d5f2c5aa72cea8e2a79e36aee322167eee7bbc0b4d23ea1c7277eb059f59cab645a144507c8db43f25a26b8b502d2d8e790f09b8fe7e61afc027e1f509ed2c25a8aa8f122af1d74378df503b0548bcc4becc2e0c2abab73cab9faefdd2d23f0c8f599efe9052e144c8fe882694103eeb543c112197a49dd391d6d2aec56b38c8589733a04c6967fbaa964a39cfc239a7c12d86d89684b304fce6ec931570b62fe41d43f4be642573a979882fb7358a622160d84461d0a5e42ca74dcff1e9571c8370be83bfa7fea908731466045e99b550279cffcc69071d8191ae0e8ac36124ec100da9057891277733f271d045949200520b8015f3016695529f2f9b3c8bc36ab89754ce2b5ac131813756c5a03d6ac9fc89e224dc0c5c079a641f1c3996cf8ee4f626f17fbe36c7406be0237e47e1e4444e223954e6a78ca68cfa4af30e18c51443f557f3cf26303a7451521095140d5494aec0d164b9ea1ce6747051db059ad1fdfc929ab63ce044d15157bd5e9c6db1c4c2f351d5c865e514d290c977d92b715999052941101ea34bfa7a78b1eaec5240827bd8e0f36b02e8cb6f33f5221103b971bb5d231e7a731b719e2d38e407c019e8bd206d084f171adcb888a51d6edcb07389887cf49fd81c3aa2a25e09949a76fbb95e9f6133e2f6dfcbd386e7808717af58269e117321ec1d2945f8df5b7fcf3bbde2be2b06ecbd61fa045ced08120d57ff1d128f7f14001736759cdb553"},{"c":"080452ea2f5485dc219c9c717b6d0aac5fdf39f54a2cd4017f1e95f1ff25499a22","p":"fae86809e8c873b2590ee3745f05af6c178ab67d6890c24970e30c2cc7d6e6c54820b352f93a5ea055cb94f113b59c2c8c450356ab4da469c1c40259a17b9bc70bc41cf5f636fd43e1c706fbc898f375a095d9e883d6b569a28f0de41541a1665053f9b5376f18c1ab6282bded8700037630e30df4e5683f7b4c46def1fa06904cdc7bc6b5f897d4d566fb74882bc9ac8b38e6c701fd8b5d38547cfe8cc6d111f527f25646a4ad89bf85d17389cb8e717a929c4addb49f6826e86ccc0be660cd6d0f16bb2656edaba02a8ed789cbab2eb505a63488b26f1d2d9637676b1d1dcf144504cefdbee5c7468b48cdd0aef4f81cfd614dc2f321b728c6e14b2e305c3a90e2a8224c1493a9a2ae6c1f354f7545668f5ff3bcdccd4d00a28d34e691bd810e3c98d79164676c615ed6fcf52df4857eb3e2757c41c539ce627b9350e7788650fa8687f28533ef5cbdbaafde8f5e9c4725eb524cd3dd03adfdb1fa22c122e297930126acf7b4aa7e155941e33e274b190f9ceb0bcb21fe2f1d3049bdfead08d6da8b577b186bed94ecefe47e8473953739a268e5a3b2ba7112a53b7b76286038cfd1b3c12ec206733748f5a7b0d81f666a6e5e8b90533bd3fcadbc390d2b67b7a6be013fd7902f19e0df51370f0a1272d3127154686a9bf8f10545b4cffaebc14526f28d0635da4d21b2a47875968c3503ec4f99fc99f5e322071fbbd251498bcec124c4ff5c517cf62448a897e25a500b08e1d96ae8fc95c4a4246be1a4ffc3d2b40e21d5f2f182486fea74d98f91904e3917a2a154fedf84ac9f8a7e485e6bca31b54dae31712f5b8337ce22a418c7da454d2cbca416828c251015a8b6655525e2b935ebd6e6151d6503e6da2d359138787885b5d6c0082baa587410b0dd366ba8cadd1bd9d95b29da5851e9518f914a7b6178d27a1ce7a5880856890e0aebb95c"}],"fee":"12000000","id":"cf7898ed-df37-411e-b87b-fda8eb5f24ab","off":"5d5424d8fa3e27dad10848ff17a95924bd9c8e9ff2adc008f237b09f6b6178cc","sigs":[{"nonce":"0279a50086f1bd83f66da38bb90056b65790b01ffc580fbafaceeb29202412baa2","xs":"020ce4f2a093034afd93251cb1876253f471431e3b1e99f6a2c4a2e52914989272"}],"sta":"S1","ver":"3:3"},null,null]}
[08/20/20 15:39:35.784+02:00] [info] [THREAD:18612] AddReceiverData(20) - Receiving 85000000 from UNKNOWN
[08/20/20 15:39:35.785+02:00] [info] [THREAD:18612] GetTxBySlateId(273) - Could not find transaction cf7898ed-df37-411e-b87b-fda8eb5f24ab
[08/20/20 15:39:35.846+02:00] [info] [THREAD:18612] AddReceiverData(55) - Adjusting original transaction offset BlindingFactor{5d5424d8fa3e27dad10848ff17a95924bd9c8e9ff2adc008f237b09f6b6178cc} by BlindingFactor{41237b67d160eaa80f0be3f0fdfe28a442003df95e5c9fec0fb78bdbba0ce489} to get total BlindingFactor{9e77a040cb9f1282e0142cf015a781c8ff9ccc99510a5ff501ef3c7b256e5d55}
[08/20/20 15:39:35.846+02:00] [info] [THREAD:18612] operator ()(141) - Adding Pubkey: PublicKey{0279a50086f1bd83f66da38bb90056b65790b01ffc580fbafaceeb29202412baa2}
[08/20/20 15:39:35.846+02:00] [info] [THREAD:18612] operator ()(141) - Adding Pubkey: PublicKey{02ddc94bc67b41494f7486bfd4a410ea6a51bdb3e845322c47d8644e7286658619}
[08/20/20 15:39:35.846+02:00] [info] [THREAD:18612] CalculateTotalNonce(147) - Total nonce: PublicKey{0288c81a15718423bc1ff4a964fc19b3ca88c43c73230fb4d1451d944c1773112a}
[08/20/20 15:39:35.846+02:00] [info] [THREAD:18612] operator ()(124) - Adding Pubkey: PublicKey{020ce4f2a093034afd93251cb1876253f471431e3b1e99f6a2c4a2e52914989272}
[08/20/20 15:39:35.846+02:00] [info] [THREAD:18612] operator ()(124) - Adding Pubkey: PublicKey{0265af930370158fa39d97da13d64067429c53409909cdec36d348f1bf888c52b2}
[08/20/20 15:39:35.846+02:00] [info] [THREAD:18612] CalculateTotalExcess(130) - Total excess: PublicKey{022d404764250ea98cf7a26328ddb8fd8479f1698d4a88eddf23ac1bfa13255219}
[08/20/20 15:39:35.847+02:00] [debug] [THREAD:18612] AddOutputs(77) - Saving output: Commitment{09baadd80006fcaae6f175936327db0e249b67c6dbe8ed93e6fba9dc77543c0ca9}
[08/20/20 15:39:35.855+02:00] [info] [THREAD:18612] Handle(93) - REPLY: {"id":1,"jsonrpc":"2.0","result":{"Ok":{"coms":[{"c":"08262dfa573c9670d9c2f72bc4f8f955f0a956e43b3fe17e1a37e2f086a44c63ef"},{"c":"096dccb99f949be8acd96957289f91ec44b5b6dd846499d0970aed1d13642f63cc","p":"2c9a5fdb98f60901e7d6acfd6484be2d1fbe2d6c0d8ebe4f92d7e6aadf673ce41d9e01e93eb98065df548216d14e971ff09d52051ebe0675fa3e8be2027251d30e10ae3ae6177dd44d831014dce1ed81854fbcd20b70a948bdd8a0f238003a61ac69319e9f4c1fe2e0a47632634db3e05237b377a3c640e5aacbe787b9da5b4efafe91943db48c85eb16df0ded9951dc8b8d5f2c5aa72cea8e2a79e36aee322167eee7bbc0b4d23ea1c7277eb059f59cab645a144507c8db43f25a26b8b502d2d8e790f09b8fe7e61afc027e1f509ed2c25a8aa8f122af1d74378df503b0548bcc4becc2e0c2abab73cab9faefdd2d23f0c8f599efe9052e144c8fe882694103eeb543c112197a49dd391d6d2aec56b38c8589733a04c6967fbaa964a39cfc239a7c12d86d89684b304fce6ec931570b62fe41d43f4be642573a979882fb7358a622160d84461d0a5e42ca74dcff1e9571c8370be83bfa7fea908731466045e99b550279cffcc69071d8191ae0e8ac36124ec100da9057891277733f271d045949200520b8015f3016695529f2f9b3c8bc36ab89754ce2b5ac131813756c5a03d6ac9fc89e224dc0c5c079a641f1c3996cf8ee4f626f17fbe36c7406be0237e47e1e4444e223954e6a78ca68cfa4af30e18c51443f557f3cf26303a7451521095140d5494aec0d164b9ea1ce6747051db059ad1fdfc929ab63ce044d15157bd5e9c6db1c4c2f351d5c865e514d290c977d92b715999052941101ea34bfa7a78b1eaec5240827bd8e0f36b02e8cb6f33f5221103b971bb5d231e7a731b719e2d38e407c019e8bd206d084f171adcb888a51d6edcb07389887cf49fd81c3aa2a25e09949a76fbb95e9f6133e2f6dfcbd386e7808717af58269e117321ec1d2945f8df5b7fcf3bbde2be2b06ecbd61fa045ced08120d57ff1d128f7f14001736759cdb553"},{"c":"080452ea2f5485dc219c9c717b6d0aac5fdf39f54a2cd4017f1e95f1ff25499a22","p":"fae86809e8c873b2590ee3745f05af6c178ab67d6890c24970e30c2cc7d6e6c54820b352f93a5ea055cb94f113b59c2c8c450356ab4da469c1c40259a17b9bc70bc41cf5f636fd43e1c706fbc898f375a095d9e883d6b569a28f0de41541a1665053f9b5376f18c1ab6282bded8700037630e30df4e5683f7b4c46def1fa06904cdc7bc6b5f897d4d566fb74882bc9ac8b38e6c701fd8b5d38547cfe8cc6d111f527f25646a4ad89bf85d17389cb8e717a929c4addb49f6826e86ccc0be660cd6d0f16bb2656edaba02a8ed789cbab2eb505a63488b26f1d2d9637676b1d1dcf144504cefdbee5c7468b48cdd0aef4f81cfd614dc2f321b728c6e14b2e305c3a90e2a8224c1493a9a2ae6c1f354f7545668f5ff3bcdccd4d00a28d34e691bd810e3c98d79164676c615ed6fcf52df4857eb3e2757c41c539ce627b9350e7788650fa8687f28533ef5cbdbaafde8f5e9c4725eb524cd3dd03adfdb1fa22c122e297930126acf7b4aa7e155941e33e274b190f9ceb0bcb21fe2f1d3049bdfead08d6da8b577b186bed94ecefe47e8473953739a268e5a3b2ba7112a53b7b76286038cfd1b3c12ec206733748f5a7b0d81f666a6e5e8b90533bd3fcadbc390d2b67b7a6be013fd7902f19e0df51370f0a1272d3127154686a9bf8f10545b4cffaebc14526f28d0635da4d21b2a47875968c3503ec4f99fc99f5e322071fbbd251498bcec124c4ff5c517cf62448a897e25a500b08e1d96ae8fc95c4a4246be1a4ffc3d2b40e21d5f2f182486fea74d98f91904e3917a2a154fedf84ac9f8a7e485e6bca31b54dae31712f5b8337ce22a418c7da454d2cbca416828c251015a8b6655525e2b935ebd6e6151d6503e6da2d359138787885b5d6c0082baa587410b0dd366ba8cadd1bd9d95b29da5851e9518f914a7b6178d27a1ce7a5880856890e0aebb95c"},{"c":"09baadd80006fcaae6f175936327db0e249b67c6dbe8ed93e6fba9dc77543c0ca9","p":"15614654d56062a5baa684bc263085e0d6269749b9ed53827dd2fd9afe65026c6352309ed37452363e325c782cabe0ff7e5967dd34540ff666143dd87d53dc230433efbc8f15b4a80fc130b055ffb2ae1fa37412edd767cf2e546870d7857a5fabe6f7523d6a8b8da2fe21aa9af0e1d50339d6bb450c2c0098a84e118dd04c631818555d779f2b94daa2b02bc3e919c7e3294c44c7e748e285a18bfe474bd5b4f9e5112a09be8c3224974d237c7a51a3276619f69d3dd2646983402b72600159216f3bfce411916c3d4486adc269b794ef7cccf0564f2fdef45b6222cf29c1ca99bd52b4636d74bdf96d6dddc48d8ce5565181873fb5923f053f46f95ee80c7c37425cc7703bef129d3c85ec77f15fa8d66a4826e574eff8e6b9a6be57a340dc5176521d00623620f356deaa56df601ea7fd245bc1069e1a4bb31d3cf978e75a694fa372e6f8ba60f8e9f186b83304680aadfcf3c37532f580ff2dd82d84bbcabbdd01b1c4b23e090c08083f596bd2f28c6a35eac61e57cad6809fd1bdfffe9ae4f46112642a882961bf5f1655d91a34376dab3c8747b2628434b2d82791840a3c45da6ce4da9431a909c0f35b60a7625517924ffeaca65c7e758ee1d0a9d328d344eb11af2fc87b05a9044a705ebcf55ea06b3acd8219d2446779d8bb6dbc388329dfa875e1668ea9f3f910f763e6c11dcf8e1b842c6691053f375561d35b2ae40ca28a6f791214784cd76fa00d1ea10594db37e81a710d8e90b0668dca88d9f9a26e447a70f5471fa7af7dfd56e68567d667f4e3f983bbf149b60d435d6ac33682aba696cb1a0da53fc4ecc5d1e7a9894d9b18aac67133b451753471116d155a394e611628ce6849810f154feb8d8e32fca25c8b44ea6b6362c784b3f5a40bcc6b7315e6cb8bd2530d2f597a5e643a63f689a7863eec67448e9f37b669716701083f"}],"id":"cf7898ed-df37-411e-b87b-fda8eb5f24ab","off":"9e77a040cb9f1282e0142cf015a781c8ff9ccc99510a5ff501ef3c7b256e5d55","sigs":[{"nonce":"02ddc94bc67b41494f7486bfd4a410ea6a51bdb3e845322c47d8644e7286658619","part":"19866586724e64d8472c3245e8b3bd516aea10a4d4bf86744f49417bc64bc9ddfec009d672111a269286e652adf125044bef2b42fbac0665f5be2396dd0d93be","xs":"0265af930370158fa39d97da13d64067429c53409909cdec36d348f1bf888c52b2"}],"sta":"S2","ver":"3:3"}}}
```

**Comment by davidtavarez** [comment] 2020-08-20 13:51
> `{"id":1,"jsonrpc":"2.0","method":"init_send_tx","params":{"args":{"amount":"85000000","estimate_only":null,"max_outputs":10,"minimum_confirmations":1,"num_change_outputs":2,"payment_proof_recipient_address":null,"selection_strategy_is_use_all":false,"send_args":{"dest":"http://3l4lltzvppekwuojkprjtnv4m7a27uhkasta6iyjxsbi7tw7vd2w2nad.grinplusplus.com","finalize":true,"fluff":false,"post_tx":true,"skip_tor":false},"src_acct_name":null,"target_slate_version":3,"ttl_blocks":null},"token":"-delete-"}}`

could you repost the Tx?

**Comment by DavidBurkett** [comment] 2020-08-20 13:56
He won't be able to post if it never finalized due to a fee dispute error.

I'm on vacation this week, but I can set up some additional logging and do some more testing with you guys when I get back.

**Comment by slavikus** [comment] 2020-11-26 10:45
I believe this issue should be closed as resolved.

**Closed** 2020-11-26 16:48 UTC
